name: crop-yield-env
channels:
- conda-forge
- pytorch
dependencies:
- python=3.9.21
- numpy=2.0.2
- pandas=2.2.3
- scikit-learn=1.6.0
- scipy=1.13.1
- matplotlib=3.9.3
- seaborn=0.13.2
- shap=0.46.0
- rasterio=1.4.3
- geopandas=1.0.1
- opencv=4.10.0
- pyproj=3.6.1
- tqdm=4.67.1
- albumentations=1.3.1
- pytorch=2.4.0
- torchvision=0.19.0
- torchaudio=2.4.0
- jupyter=1.0.0
- folium=0.19.0
- gdal=3.6.0
- xarray=2024.7.0
- pykrige=1.7.2
- fiona=1.10.1
- shapely=2.0.6
- openpyxl=3.1.5
- notebook=7.1.2
- cudatoolkit=11.8
